// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240721210618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s24",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s25",
                            Price = 16000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s26",
                            Price = 17000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s27",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s28",
                            Price = 19000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s29",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Phone",
                            Description = "a good phone",
                            Name = "samsung s30",
                            Price = 21000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
