// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiApp.Models;

#nullable disable

namespace _7__WebAPIApp.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240714180040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 65000m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 70000m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Iphone 17",
                            Price = 75000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
